### ISSUE TITLE
Switch from Datomic to RocksDB

### ISSUE THREAD

**Issue by alexanderkiel** [samply/blaze#120]
This move is quite a big one so I try to explain my reasons for it.

Here are two main points:
* Datomic isn't open source and [Datomic Free](https://my.datomic.com/downloads/free) isn't maintained since 2018
* a suitable database backend for FHIR Server looks more like a combination of a document store and indices for each [search parameter](https://www.hl7.org/fhir/search.html)

For the first point it's important to know that my organization currently is paying for Datomic. I don't say that everything should be free as in beer. I also don't plan to comment on the way [Cognitect](https://cognitect.com) likes to market Datomic. But for Blaze as an open source project and especially currently more an academic prototype, it's important that everyone can try Blaze freely. There is a Datomic Pro Starter edition which can be obtained without costs, but I can't ship Datomic Pro Starter with Blaze. So if I like to use the functionality of Datomic Pro, a simple `docker run` would not work anymore. Everyone who likes to try Blaze has to get their own copy of Datomic Pro Starter first.

The second point is more interesting and is the main reason for the switch. A FHIR server for the most part is a simple CRUD API for FHIR resources. In nearly all cases you will receive the whole resource without any change. So a document store seams more suitable to this task where you simply store a whole resource as blob. On the other hand with Datomic, I had to cut resources into triples on import and put them together again on export.

On top of the simple CRUD operations, there is [FHIR search](https://www.hl7.org/fhir/search.html). In FHIR search it's important to understand that it's not defined on the attributes of the resources itself, but it's defined on special search parameters. In Datomic you would mark an attribute of a resource as indexed, giving you index access to values of this attribute. But in FHIR in nearly all cases, search parameters aren't an 1:1 function of attributes. For example the search value for a typical [CodeableConcept](https://www.hl7.org/fhir/datatypes.html#CodeableConcept) attribute is simply `code-system|code` were the CodeableConcept is a rather complex data type of it's own. The consequence is that putting secondary indices on the attributes of a resource itself isn't sufficient for a FHIR server. That also means, like I said earlier, that cutting a resource into triples has no value. The implementation of Blaze in version 0.7 was focused on CQL, so it didn't implement search parameters at all. With the switch to RocksDB, search parameters were considered for the first time.

On the background of extensive indexing requirements of the various search parameters, not to mention [Variant Searches](https://www.hl7.org/fhir/http.html#vsearch), indexing performance is important. Especially indexing performance is a part were Datomic has room for improvement. Datomic's write pipeline is more or less single threaded. I never saw more than 3 threads used by the Transactor. There were plans to improve on this, but it never happened.

The switch to RocksDB is heavily inspired by [Crux](https://opencrux.com). Although for a FHIR server the bitemporality isn't required, many ideas from Crux had a good fit for Blaze:
* document based architecture
* content based tasing of document versions
* separating indices from time (content based indices)
* use of local, embedded RocksDB because disks are faster than network nowadays

Non fits of Crux are:
* bitemporality 
* attribute based indexing

In the document based architecture of Crux, each version of a document is hashed by content, the same way Git works. That document versions are stored in a document store, keyed by their content hashes. In addition to that document store, an index of document ID and time points to the content hash. With the help of this index, one can retrieve the content hash of a document at a certain point in time.

That architecture differs from Datomics Triples+Time in a way that the time is appended to each triple, where in Crux the time of only appended to each document and more precisely to each content hash. This architecture has various implications.

To start with a disadvantage, each update to a document requires to store the whole new version of it, in contrast to Datomics model, where only newly added and retracted triples need to be stored. So if you only change a small portion of a Datomic entity, Datomic will be much more space efficient. On the other hand, Datomic has to reconstruct whole entities from triples spread over time, where in Crux, one simply determines the content hash of the whole document at the point in time of interest and can fetch the whole document in one operation.

Especially for indexing performance, the separation of document content and time is important. One part of the database consists only of document content, indices on that content and the content based hashes. The other part of the database consists of time involving indices to content based hashes alone. This separation of concerns has big implications on transaction handling. Where the decision whether a transaction should commit or be rolled back will need to be serialized and so can't be run in parallel, indexing can run parallel. The reason for this is that it doesn't matter if document versions are stored and indexed in the first part of the database as long as the are not referenced in the second part. So indexing can run parallel to transaction handling. In case a constrain violation leads to an aborted transaction, it is sufficient to not store the tiny part of data which consists only of document ID's time and content hashes. All previously stored and indexed documents don't hurt, because they are not referenced in the time-based part of the database. Excessive stored and indexed documents can be garbage collected by a background task.

Another aspect is the use of an embedded RockDB database engine with local disk storage instead of only an embedded query engine with network attached, central storage used in Datomic. Datomic was designed in 2012 (8 years) ago where SSD's weren't common in servers. With spinning disks, accessing data over network in a central storage with in-memory caching and many disks was faster than local disk access. Nowadays, local NVMe SSD's are the fastest data access path. Without any additional caching infrastructure like memcached and also the more recently introduced SSD cache, Datomic relies solely on in-process memory caching. As a consequence, Datomic is super slow after an application restart. On the other hand, a application using RocksDB doesn't suffer from this slowness, because it can rely on the operating system page cache which caches accessed files.

The decision to only use ideas from Crux instead of building on top of it, originates from the fact that the bitemporality is of no use in a FHIR server and that for reasons laid out earlier, attribute based indexing is also not useful. Another aspect is that Crux itself is in a very alpha stage which itself doesn't help if one have to modify it considerably. But some of the key concepts are a very good fit in my eyes and so I just used them in my implementation.

I will describe the implementation later in the Blaze documentation. For now the switch to RocksDB brings the following advantages:
* nearly full support of FHIR search parameters
* about 10x higher indexing performance
* first time 100% Touchstone basic test conformance
* much improved cold CQL query performance
* removal of the all-patient list cache for CQL
* replacement of the quite hacky special Datomic indexing attributes with variant search indexes for the patient compartment, expandable to other compartments 
* no need for a terminology server during import
* no need for a separate Datomic database instance. a local directory is sufficient

and also disadvantages:
* only one replica of Blaze is supported. multiple replicas will be possible after implementing coordination through Postgres or Kafka like shown in Crux

**Comment by alexanderkiel** [comment]
@drewverlee This move is the main reason I was so quiet in the last months. I know that you rely on Blaze using Datomic. But I just had to prototype whether such a switch was feasible for my use case. Now that the implementation is in a stable state, I can make the switch public. Unfortunately I'm sorry if that means for you that you have to life with a fork of Blaze. I somehow hope that Blaze is still useful for you and would be more than happy to continue the collaboration.

**Comment by dspiteself** [comment]
When we fork would you like us to change the name and give credit or use the "blaze" and use a modifier like v1?

**Comment by dspiteself** [comment]
Thanks for blaze! It has been very nice to work with. There will probably still be many places to collaborate and possibilities of shared modules. We have a plan to resolve most of the indexing issues. Pro datomic has [valcache](https://docs.datomic.com/on-prem/valcache.html) to resolve some of the cold query issues. Thanks again.

**Comment by alexanderkiel** [comment]
> When we fork would you like us to change the name and give credit or use the "blaze" and use a modifier like v1?

I would like you to change the name.

**Comment by alexanderkiel** [comment]
> There will probably still be many places to collaborate and possibilities of shared modules. 

I would be more than happy to work together on shared modules. In my opinion, if we manage to share modules over different database backends, the code quality and overall architecture would improve.

> We have a plan to resolve most of the indexing issues. 

Would be definitely interesting to see this.

> Pro datomic has [valcache](https://docs.datomic.com/on-prem/valcache.html) to resolve some of the cold query issues.

Yes I know and I also mentioned the flash based storage cache above. It would be perfect to have a free edition without this feature but with the same API as the pro edition. Performance is always a good motivator to upgrade to a paid plan. But things are different.

**Comment by drewverlee** [comment]
Echoing @dspiteself sentiment. Thanks for putting blaze out there and helping us use it. We look forward to future collaboration.
