### ISSUE TITLE
Support filtering for elements in CapabilityStatement

### ISSUE THREAD

**Issue by DWay17** [samply/blaze#1250]
I would like to query things like `/fhir/metadata?_elements=status,software` to only see version and if its running ...

**Comment by alexanderkiel** [comment]
Good idea. Did not know that this is even specified. The spec can be found [here](https://hl7.org/fhir/http.html#capabilities).

**Comment by alexanderkiel** [comment]
@DWay17 Thanks for reporting. This feature will come in v0.23.2 maybe next week.
