### ISSUE TITLE
Preserve Value Order of Multi-Valued Elements

### ISSUE THREAD

**Issue by alexanderkiel** [samply/blaze#15]
In JSON multi-values elements are represented by lists. That lists have an order. In Datomic multi-values elements are sets. We have to create our own list implementation here to revere order. Also keep an eye on performance.

For most data elements the order of its values has no meaning. Only in case [ElementDefinition.orderMeaning](https://www.hl7.org/fhir/elementdefinition.html) is present, the order has a meaning. So we might mostly ok with not preserving the order. But for example [HumanName.given](https://www.hl7.org/fhir/datatypes-definitions.html#HumanName.given) has an `orderMeaning`.

**Comment by dspiteself** [comment]
Currently for HumanName.given  we make it cardinality 1 and use a [ascii null](https://en.wikipedia.org/wiki/Null_character) as a separator. Then we split and join as it gets to the edge of the database. 
We were planning to use [homogeneous-tuples](https://docs.datomic.com/on-prem/schema.html#homogeneous-tuples) for some cases and a tuple with order and value for other cases.

**Comment by alexanderkiel** [comment]
In R4 there are only 5 data elements with an `orderMeaning`:

| Element | Data Type | orderMeaning |
| :--- | :--- | :--- |
| Address.line | string | The order in which lines should appear in an address label |
| HumanName.given | string | Given Names appear in the correct order for presenting the name |
| HumanName.prefix | string | Prefixes appear in the correct order for presenting the name |
| HumanName.suffix | string | Suffixes appear in the correct order for presenting the name |
| Bundle.entry | BackboneElement | For bundles of type 'document' and 'message', the first resource is special (must be Composition or MessageHeader respectively). For all bundles, the meaning of the order of entries depends on the bundle type |

I expected more. Do I miss some? So we have only two cases, string typed elements and the `Bundle.entry` element.

FHIR discourages one from using the null char in [strings](https://www.hl7.org/fhir/datatypes.html#string):
>Strings SHOULD not contain Unicode character points below 32, except for u0009 (horizontal tab), u0010 (carriage return) and u0013 (line feed).

So the use of the null char as separator is a valid idea.

Using tuples with order and value might be a good fit for `Bundle.entry`. But we can't use tuples in the Free edition. I don't really need to store bundles for my use cases.

Independent of `orderMeaning` there is the value set [List Order Codes](https://www.hl7.org/fhir/valueset-list-order.html) which also gives order meaning to `List.entry`, `Composition.section.entry` and others. What should be do here? I'll ask in the FHIR chat whether `orderMeaning` should be present for that elements.

**Comment by alexanderkiel** [comment]
Thread in #implementers is [here](https://chat.fhir.org/#narrow/stream/179166-implementers/topic/Missing.20orderMeaning.20on.20List.2Eentry.3F).

**Comment by dspiteself** [comment]
you can do an :order attribute if the type was a :db.type/ref like bundle

**Comment by alexanderkiel** [comment]
Is solved by switching to RocksDB.
