### ISSUE TITLE
Chained search filter not applied

### ISSUE THREAD

**Issue by Mandalka** [samply/blaze#1588]
The filter of f.e. following query is not working:

`/fhir/Procedure?encounter.diagnosis:Condition.code=mydiagnosiscodeA,mydiagnosiscodeB,mydiagnosiscodeX`

Blaze returns all procedures on the FHIR Server (and does not append the filter paremeters to results bundle "link" URLs like "self" or "next").

Not sure if relevant: encounter.diagnosis cardinality of the FHIR resources can be/is often more than 1.

Version of Blaze is the version of current release of MII Feasibility deploy.

From /fhir/metadata:
```
<software>
<name value="Blaze"/>
<version value="0.23.2"/>
<releaseDate value="2023-11-26"/>
</software>
```

**Comment by alexanderkiel** [comment]
If you run the FHIR search query with the HTTP header `Prefer: handling=strict` as suggested [here](https://www.hl7.org/fhir/search.html#errors), you will get the following error:

```json
{
  "issue": [
    {
      "severity": "error",
      "code": "not-supported",
      "diagnostics": "Search parameter chains longer than 2 are currently not supported. Please file an issue."
    }
  ],
  "resourceType": "OperationOutcome"
}
```
Can you please file a new issue requesting to support parameter chains longer than 2? I'll close this issue.
