### ISSUE TITLE
Import resource twice (same id) doubles volume size

### ISSUE THREAD

**Issue by martinbreu** [samply/blaze#207]
Import the same resources in **blaze:0.7.0** results in same volume size, but for **blaze:0.8.0-beta.3** it seems to keep the old resource, so space doubles. Maybe it's not a bug, but updating Blaze once a week through Talend (Just repeating all resource updates with same ids), results in a weekly storage space growth of over 1GB in my case.

A feature to delete old resources would be nice ;)

**Comment by martinbreu** [comment]
A restart of Blaze releases the space

**Comment by alexanderkiel** [comment]
I will close this because a restart fixes this.
