### ISSUE TITLE
Add bundle of episode with period without timezone returns bad request

### ISSUE THREAD

**Issue by kairosmike** [samply/blaze#284]
I have not tested yet, but I am almost sure, that balze v.0.8.0 excepted periods also without time zone.

Valid example request:
```
curl --request POST \
  --url http://localhost:9090/fhir \
  --header 'Content-Type: application/json' \
  --data '{
	"resourceType": "Bundle",
	"type": "batch",
	"entry": [
		{
			"fullUrl": "Encounter/6161",
			"resource": {
				"resourceType": "Encounter",
				"id": "6161",
				"meta": {
					"profile": [
						"http://dktk.dkfz.de/fhir/StructureDefinition/onco-core-Encounter-Fall"
					]
				},
				"status": "unknown",
				"class": {
					"system": "https://www.hl7.org/fhir/v3/ActEncounterCode/vs.html",
					"code": "unknown"
				},
				"subject": {
					"reference": "Patient/1137946"
				},
				"period": {
					"start": "2019-11-17T00:00:00+01:00",
					"end": "2020-11-17T00:00:00+01:00"
				}
			},
			"request": {
				"method": "PUT",
				"url": "Encounter/6161"
			}
		}
	]
}'
```

Unvalid request:
```
curl --request POST \
  --url http://localhost:9090/fhir \
  --header 'Content-Type: application/json' \
  --data '{
	"resourceType": "Bundle",
	"type": "batch",
	"entry": [
		{
			"fullUrl": "Encounter/6161",
			"resource": {
				"resourceType": "Encounter",
				"id": "6161",
				"meta": {
					"profile": [
						"http://dktk.dkfz.de/fhir/StructureDefinition/onco-core-Encounter-Fall"
					]
				},
				"status": "unknown",
				"class": {
					"system": "https://www.hl7.org/fhir/v3/ActEncounterCode/vs.html",
					"code": "unknown"
				},
				"subject": {
					"reference": "Patient/1137946"
				},
				"period": {
					"start": "2019-11-17T00:00:00",
					"end": "2020-11-17T00:00:00"
				}
			},
			"request": {
				"method": "PUT",
				"url": "Encounter/6161"
			}
		}
	]
}'
```

Response:
`{"issue":[{"severity":"error","code":"invariant","diagnostics":"Error on value `{:resourceType \"Encounter\", :id \"6161\", :meta {:profile [\"http://dktk.dkfz.de/fhir/StructureDefinition/onco-core-Encounter-Fall\"]}, :status \"unknown\", :class {:system \"https://www.hl7.org/fhir/v3/ActEncounterCode/vs.html\", :code \"unknown\"}, :subject {:reference \"Patient/1137946\"}, :period {:start \"2019-11-17T00:00:00\", :end \"2020-11-17T00:00:00\"}}`. Expected type is `Resource`.","expression":["entry[0].resource"]}],"resourceType":"OperationOutcome"}`

**Comment by kairosmike** [comment]
I tested again: blaze v.0.8.0 accepts NO FHIR DateTimeType without time zone. 

sorry..wrong memories!

**Comment by alexanderkiel** [comment]
The [dateTime](https://www.hl7.org/fhir/datatypes.html#dateTime) type requires time zones whenever hours or minutes are given. The spec says:

>If hours and minutes are specified, a time zone SHALL be populated.

So I would not change the behavior to require a time zone. However I improved the error message through #224.
