### ISSUE TITLE
Fix Processing of Empty Transaction Bundles

### ISSUE THREAD

**Issue by kairosmike** [samply/blaze#288]
_Tested with blaze.v.0.10.0_
1. Request returns a valid response. Organization has been created und might be updated multiple times. 
```
curl --request POST \
  --url http://localhost:9090/fhir \
  --header 'Content-Type: application/json' \
  --data '{
	"resourceType": "Bundle",
	"type": "transaction",
	"total": 3,
	"entry": [
		{
			"fullUrl": "Organization/294939",
			"resource": {
				"resourceType": "Organization",
				"id": "294939",
				"meta": {
					"profile": [
						"http://dktk.dkfz.de/fhir/StructureDefinition/onco-core-Organization-organisation"
					]
				},
				"identifier": [
					{
						"system": "urn:centraxx:org",
						"value": "ONKOLOGIE"
					}
				],
				"active": true,
				"type": [
					{
						"coding": [
							{
								"system": "https://www.hl7.org/fhir/valueset-organization-type.html",
								"code": "dept",
								"display": "Hospital Department"
							}
						]
					}
				],
				"name": "Children Oncology"
			},
			"request": {
				"method": "PUT",
				"url": "Organization/294939"
			}
		}
	]
}'
```
2. Request: leads to a NPE
```
curl --request POST \
  --url http://localhost:9090/fhir \
  --header 'Content-Type: application/json' \
  --data '{
  "resourceType": "Bundle",
  "type": "transaction",
  "total": 0
}'
```
Response
`{"issue":[{"severity":"error","code":"exception","diagnostics":"                               \u001B[37mjava.lang.Thread.run\u001B[m  \u001B[32m            Thread.java:  834\u001B[m\r\n \u001B[37mjava.util.concurrent.ThreadPoolExecutor$Worker.run\u001B[m  \u001B[32mThreadPoolExecutor.java:  628\u001B[m\r\n  \u001B[37mjava.util.concurrent.ThreadPoolExecutor.runWorker\u001B[m  \u001B[32mThreadPoolExecutor.java: 1128\u001B[m\r\n\u001B[37mjava.util.concurrent.CompletableFuture$AsyncRun.run\u001B[m  \u001B[32m CompletableFuture.java: 1736\u001B[m\r\n                             \u001B[33mblaze.db.node.Node/\u001B[1;33mrun\u001B[m  \u001B[32m               node.clj:  293\u001B[m\r\n                              \u001B[33mblaze.db.node.Node/\u001B[1;33mfn\u001B[m  \u001B[32m               node.clj:  294\u001B[m\r\n                                 \u001B[33mblaze.db.node/\u001B[1;33mpoll\u001B[m  \u001B[32m               node.clj:  173\u001B[m\r\n                        \u001B[33mblaze.db.node/\u001B[1;33mindex-tx-data\u001B[m  \u001B[32m               node.clj:  152\u001B[m\r\n                             \u001B[33mblaze.db.node/\u001B[1;33mindex-tx\u001B[m  \u001B[32m               node.clj:  118\u001B[m\r\n                  \u001B[33mblaze.db.node.tx-indexer/\u001B[1;33mindex-tx\u001B[m  \u001B[32m         tx_indexer.clj:   51\u001B[m\r\n        \u001B[33mblaze.db.node.tx-indexer/\u001B[1;33msort-by-references\u001B[m  \u001B[32m         tx_indexer.clj:   43\u001B[m\r\n           \u001B[33mblaze.db.node.tx-indexer/\u001B[1;33mreference-order\u001B[m  \u001B[32m         tx_indexer.clj:   32\u001B[m\r\n           \u001B[33mblaze.db.node.tx-indexer/\u001B[1;33mreference-graph\u001B[m  \u001B[32m         tx_indexer.clj:   20\u001B[m\r\n                                                \u001B[37m...\u001B[m  \u001B[32m                             \u001B[m\r\n                                 \u001B[33mloom.graph/\u001B[1;33mdigraph\u001B[m  \u001B[32m             graph.cljc:  521\u001B[m\r\n                                 \u001B[33mloom.graph/\u001B[1;33mdigraph\u001B[m  \u001B[32m             graph.cljc:  525\u001B[m\r\n                                 \u001B[33mclojure.core/\u001B[1;33mapply\u001B[m  \u001B[32m               core.clj:  667\u001B[m\r\n                                                \u001B[37m...\u001B[m  \u001B[32m                             \u001B[m\r\n                             \u001B[33mloom.graph/\u001B[1;33mbuild-graph\u001B[m  \u001B[32m             graph.cljc:  478\u001B[m\r\n                             \u001B[33mloom.graph/\u001B[1;33mbuild-graph\u001B[m  \u001B[32m             graph.cljc:  513\u001B[m\r\n                                \u001B[33mclojure.core/\u001B[1;33mreduce\u001B[m  \u001B[32m               core.clj: 6827\u001B[m\r\n                                                \u001B[37m...\u001B[m  \u001B[32m                             \u001B[m\r\n                       \u001B[33mloom.graph/build-graph/\u001B[1;33mbuild\u001B[m  \u001B[32m             graph.cljc:  499\u001B[m\r\n                                   \u001B[33mclojure.core/\u001B[1;33mval\u001B[m  \u001B[32m               core.clj: 1579\u001B[m\r\n\u001B[1;31mjava.lang.NullPointerException\u001B[m: \u001B[3m\u001B[m\r\n"}],"resourceType":"OperationOutcome"}`

After the NPE the 1. request (and all other I have tried) leads to the same NPE. After a restart of blaze with empty database, the 1. request is fine again.

**Comment by alexanderkiel** [comment]
I can confirm this issue. The root cause is, processing an empty collection of transaction operations at all.
