### ISSUE TITLE
Suchparameter nicht unterstützt

### ISSUE THREAD

**Issue by stolzA** [samply/blaze#377]
Auf die Anfrage
```
Patient?_has:MedicationAdministration:patient:medication.code=C09AA05&_summary=count
```
bekommt man folgende Fehlermeldung:
```
http://localhost:8080/fhir/Patient?%3A%3Acognitect.anomalies%2Fnot-found=&%3AThe+search-param+with+code+%60medication.code%60+and+type+%60MedicationAdministration%60+was+not+found.=&_summary=count&_count=50&__t=61
```

Version v0.11.0-beta.1

**Comment by alexanderkiel** [comment]
Here, the problem is the missing support for forward chaining which is required for `medication.code`. An issue to implement this exists already in #294. Please vote for it.
