### ISSUE TITLE
Add support to the REST API to search with FHIR search reference parameters

### ISSUE THREAD

**Issue by drewverlee** [samply/blaze#49]
Greetings, Thanks for taking the time to consider this issue. Our team is ready and happy to tackle this issue asap. Recommendations and feedback welcome!

## Problem

The Blaze REST API doesn't support searching with [FHIR search reference parameters](https://www.hl7.org/fhir/search.html#reference) Which allows for Searching Resources by a field on that resource that is a reference type.

Currently, it only supports: `_summary` and `identifier`. Which are documented in the CapabilityStatment which is accessible at [base]/fhir/metadata (where base would be the host and port of your blaze server blaze:8080)

An example of a http request url query that currently isn't supported. This url also opens to a public fhir server so we can see the results:

http://hapi.fhir.org/baseR4/MedicationRequest?subject=1200

Here The [MedicationRequest](https://www.hl7.org/fhir/medicationrequest.html) [subject](https://www.hl7.org/fhir/medicationrequest-definitions.html#MedicationRequest.subject)
is of Type Reference. This is important because it directly relates to the FHIR search reference parameters specification linked above.Meaning, the search params specification documents how to send a GET request to query that relationship.

## Purposed Solution

Add a feature to allow Blaze to Generate REST api endpoints dynamically based off FHIR data.

### Implementation details

This can be broken into essential two parts

- get search parameters schema from.
- extend blaze search to use search params

The FHIR schema containing the Reference paramaters specification is encoded in this [fhir definitions download link](http://www.hl7.org/fhir/definitions.json.zip) downloads a set of files including `search-paramaters.json`.  This can be used to verify the reference parameters and build the lookup.

## Context

Blaze version: 0.6.2

## related issues

#33 : mentions enabling fhirs "_revinclude" functionality, which gets us the desired ability to query
resources by Patient, but i believe will return more data then we want because were loading data on demand.
e.g When the user loads the medications page, thats when we hope to request both the page and data for there medications. This
saves us having to load that data when they first visit the site and keeps response times down.

**Comment by alexanderkiel** [comment]
I've already read your proposal some days ago. Please give me more time to think about it in more detail.

**Comment by dspiteself** [comment]
The current approach does a scan of all resources of that type. In order to make use of indexes everything including those of type bytes would need to be defined in a way that their sort order is correct. We are implementing (locally in a temporary fork) something that extends the current approach for now, but I would like to see something more index based here. I would be happy to make other issues along those lines. 

One more note a [vase](https://github.com/cognitect-labs/vase) like approach is great to bring more observability to these generated endpoints. I am not saying use vase I am just saying the approach is nice.

**Comment by dspiteself** [comment]
The  answer to this question is at the end of #50 .

**Comment by drewverlee** [comment]
greetings again, 

Here is how were currently solving the search problem on our fork of blaze. 
This might give you some insight into how you want to handle it.

In blaze.edn we define a :blaze.interaction/search-type per resource

e.g  Here is how we handle Condition, we pass it a list of codes matched with their [expressions](https://www.hl7.org/fhir/searchparameter-definitions.html#SearchParameter.expression)

```Clojure
  [:blaze.interaction/search-type :blaze.interaction.search/Condition]
  {:database/conn                     #blaze/ref :blaze.datomic/conn
   :blaze.fhir.SearchParameter/config [{:blaze.fhir.SearchParameter/code       "patient"
                                        :blaze.fhir.SearchParameter/expression [:Condition/subject :Patient/id]}
                                       {:blaze.fhir.SearchParameter/code       "category"
                                        :blaze.fhir.SearchParameter/expression [:Condition/category :CodeableConcept/coding :Coding/code :code/code]}]}
```

This works with our modified version of the search_type namespace. Where we have changed
resource pred to take a `config` map that contains the `code` and `expression` from above.
These inform the search how to filter via the expression per code which mostly happens in the `match?` function. 

```Clojure
(defn- match?
  [tree path search]
  (let [k       (first path)
        subtree (get tree k)]
    (cond
      (nil? k)       (= search tree)
      (nil? subtree) false
      (set? subtree) (some (fn [st] (match? st (rest path) search))
                           subtree)
      :else          (match? subtree (rest path) search))))

(defn- resource-pred [query-params config]
  (let [valid-query-params  (select-keys query-params (map :blaze.fhir.SearchParameter/code config))
        select-path-by-code (fn [config code]
                              (->> config
                                   (filter #(= (:blaze.fhir.SearchParameter/code %) code))
                                   first
                                   :blaze.fhir.SearchParameter/expression))]
    (when (seq valid-query-params)
      (fn [resource] (every? (fn [[path search]] (match? resource path search))
                            (mapv (fn [[k v]] [(select-path-by-code config k) v]) valid-query-params))))))
```


The rest of the search type handler is then opended up to pass these arguments. note this code is mostly the same, were must passing
the searchparam config along with the connection.

```Clojure
(defn- handler-intern [{:keys [database/conn blaze.fhir.SearchParameter/config]}]
  (fn [{{{:fhir.resource/keys [type]} :data} ::reitit/match
       :keys [params]
       ::reitit/keys [router]}]
    (-> (search router (d/db conn) type params config)
        (ring/response))))

(defn handler
  ""
  [config]
  (-> (handler-intern config)
      (wrap-params)
      (wrap-observe-request-duration "search-type")))


(defmethod ig/init-key :blaze.interaction/search-type
  [_ config]
  (log/info "Init FHIR search-type interaction handler")
  (handler config))
```

Hopefully this helps!

**Comment by alexanderkiel** [comment]
Ok that looks good. You then put the `:blaze.interaction.search/Condition` key in `:blaze/rest-api` under the `Condition` type - right? Integrant instantiates then a `:blaze.interaction/search-type` with the corresponding `:blaze.fhir.SearchParameter/config`.

How do you plan to handle the different types of search parameters like token, string or reference?

The search is still not indexed. Is that ok for you in a first iteration?

**Comment by drewverlee** [comment]
>  You then put the :blaze.interaction.search/Condition key in :blaze/rest-api under the Condition type - right? 

correct. e.g 

```Clojure
  [:blaze.interaction/search-type :blaze.interaction.search/Condition]
  {:database/conn                     #blaze/ref :blaze.datomic/conn
   :blaze.fhir.SearchParameter/config [{:blaze.fhir.SearchParameter/code       "patient"
                                        :blaze.fhir.SearchParameter/expression [:Condition/subject :Patient/id]}
                                       {:blaze.fhir.SearchParameter/code       "category"
                                        :blaze.fhir.SearchParameter/expression [:Condition/category :CodeableConcept/coding :Coding/code :code/code]}]}
```
How do you plan to handle the different types of search parameters like token, string or reference?

I don't have a strategy for the other types currently. 

> The search is still not indexed. Is that ok for you in a first iteration?

I'm not sure, will probably proceed assuming its ok and then benchmark if we notice things are too slow.

**Comment by alexanderkiel** [comment]
Would it be an idea to parse SeachParameter definitions directly instead of having to write them down by hand?

**Comment by dspiteself** [comment]
Yes It would. We plan on generating chunks of our blaze.edn from that data. but some of the expressions are non trivial to generate optimally. We would like to give ourselves hooks at least until we know we can read the `SeachParameter`s we want.  Also this comes back to the possibility of different schema choices. If someone decided they wanted to use tuples to make a better index. We would like that flexibility somewhere.
