### ISSUE TITLE
Fix Status Code of Type-Level $evaluate-measure Operation

### ISSUE THREAD

**Issue by alexanderkiel** [samply/blaze#512]
A request to `[base]/Measure/$evaluate-measure` returns a 404 if the measure was not found. However it should return a 422 Unprocessable Entity on POST requests and a 400 Bad Request on GET requests because the resource itself exists.

**Comment by allentiak** [comment]
Fixed by https://github.com/samply/blaze/commit/bedf203ae8cf770dad68673cc3639bab027872ec.
