### ISSUE TITLE
401 errors on batched request

### ISSUE THREAD

**Issue by migraf** [samply/blaze#627]
Hi,
i've been using blaze FHIR server for a while now and really like it!
I´ve run into a problem though:
When using batched get requests to a server using OIDC authentication, as described in your example, the batched-response shows 401 errors for the requested resources. The following is the request body of an example batch request that results in an error when posting against the base API endpoint.

```json
{
    "entry": [
        {
            "request": {
                "method": "GET",
                "url": "Patient/C7VKNEIOC5SOL3L2"
            }
        },
        {
            "request": {
                "method": "GET",
                "url": "Patient/C7VKNEIOC5SOL3L4"
            }
        },
        {
            "request": {
                "method": "GET",
                "url": "Patient/C7VKNEIOC5SOL3L3"
            }
        }
    ],
    "type": "batch",
    "resourceType": "Bundle"
}
```

Resulting in the following response: 

```json
{
    "id": "C7Z3Y2QO7FZYW4EP",
    "type": "batch-response",
    "entry": [
        {
            "response": {
                "status": "401"
            },
            "resource": {
                "issue": [
                    {
                        "severity": "error",
                        "code": "login",
                        "details": {
                            "coding": [
                                {
                                    "system": "http://terminology.hl7.org/CodeSystem/operation-outcome",
                                    "code": "MSG_AUTH_REQUIRED"
                                }
                            ]
                        }
                    }
                ],
                "resourceType": "OperationOutcome"
            }
        }, // rest emmited for brevity
    "resourceType": "Bundle"
}
```

Querying the same resources directly i.e. by requesting `localhost:8080/fhir/Patient/C7VKNEIOC5SOL3L2` (using the same headers) does not result in an unauthorized exception and returns the requested resource.

Do you  have an idea on how i could solve this issue. Is there a different way of passing credentials to the individual requests in the batch?
Thank your for your work & help :)

**Comment by alexanderkiel** [comment]
Fixed in [v0.16.2](https://github.com/samply/blaze/releases/tag/v0.16.2). Thanks for reporting.
