### ISSUE TITLE
BASE_URL Prioritization over Dynamic Conf. 

### ISSUE THREAD

**Issue by NamUKF** [samply/blaze#820]
Hi, 

i have a apache Reverse Proxy, which I want to use to proxy multiple different blaze FHIR Server. 

My preferred solution requires the usage of several Locations in a single virtual host. 
Reason for that is, that we don't want to use wildcard certificates in for the reverse proxy and having to change the SSL cert SAN for each fhir server that joins, is a hassle, which is the reason I want to know, whether the it is possible to add a location as part of the base_URL. 

https://github.com/samply/blaze/blob/master/docs/api.md

Meaning the BASE URL will be `server-1:443/blaze-server-1/fhir/Patient`
And for the second server `server-1:443/blaze-server-2/fhir/Patient`

The Conf looks something like this:

```
<VirtualHost *:443>
      ServerName fhir.server1.uniklinik-freiburg.de
      ServerAlias fhir.server1.ukl.uni-freiburg.de

     RequestHeader set X-Forwarded-Proto expr=%{REQUEST_SCHEME}
     ProxyPreserveHost On

     <Location "/blaze-server-1">
 
         ProxyPass "http://locallink:8080"
        ProxyPassReverse "http://locallink:8080"
   </Location>
    <Location "/blaze-server-2">
 
         ProxyPass "http://locallink:8080"
        ProxyPassReverse "http://locallink:8080"
   </Location>
</VirtualHost>
```

Given current config, the generated URL (next, self etc.) however will remove the "blaze-server-1" part of the URL, which I want to ask here, whether it is possible to prioritiize the static BASE_URL Env Var, over the dynamic version or not. 
because in there it is fully written, which is applicable for starting the server. as said the gernerated links however don't consider that. 
Any help appreciated.

Thanks !

**Comment by alexanderkiel** [comment]
Yes that should be possible. Please try to set the [CONTEXT_PATH](https://github.com/samply/blaze/blob/master/docs/deployment/environment-variables.md) env var on one instance of Blaze to `blaze-server-1` and on the other to `blaze-server-2`. You could also add `/fhir` but that is not necessary. `/fhir` is only the default. In addition to `CONTEXT_PATH`, you can set the `BASE_URL` to the URL without the context path or you can configure `X-Forwarded-Host` in nginx as described [here](https://github.com/samply/blaze/blob/master/docs/deployment/environment-variables.md#base_url).

**Comment by NamUKF** [comment]
thanks a lot, i should've checked the env vars first. Anyways with that config it works. Though i have to ask, setting the HTTP Headers, should only influence the BASE_URL and not the CONTEXT_PATH. Correct ?

**Comment by alexanderkiel** [comment]
> thanks a lot, i should've checked the env vars first. Anyways with that config it works. Though i have to ask, setting the HTTP Headers, should only influence the BASE_URL and not the CONTEXT_PATH. Correct ?

Yes because the headers can only influence the protocol, host and port.
