### ISSUE TITLE
CQL with reference to a familymemberhistory

### ISSUE THREAD

**Issue by CzarMich** [samply/blaze#871]
I am writing a cql that works but when I Include reference to a condition that  is genetic, 
(related to father or mother), it doe not work.
could this be a known issues?

Or could you be having an example of a  cql that makes reference to familymemberhistory ? Or could it be I not writing it correctly:

define Risk_Inclusion:
exists ([FamilyMemeberHistory: Condition.Code.Coding.Code '38341003' from SNOMED]FMH where FMH.relationship =father) or
exists ([FamilyMemeberHistory: Condition.Code.Coding.Code '38341003' from SNOMED]FMH where FMH.relationship = mother) or

I will be glad fro any help here.

Thanks.

**Comment by alexanderkiel** [comment]
@CzarMich Sorry for not noticing your issue. Is it still relevant?

**Comment by CzarMich** [comment]
No, not relevant now. 

Thank you.
