### ISSUE TITLE
Count query with _profile parameter takes minutes to complete

### ISSUE THREAD

**Issue by philwinn** [samply/blaze#939]
A blaze instance (version 0.20.1) with ~27M `MedicationAdministration` resources takes more than 3 minutes to complete the following query:
```
MedicationAdministration?_profile=https://www.medizininformatik-initiative.de/fhir/core/modul-medikation/StructureDefinition/MedicationAdministration&_summary=count
```
With the result:
```json
{
  "id": "DBW2LGK5N4K2CORT",
  "type": "searchset",
  "total": 27669756,
  "link": [
    {
      "relation": "self",
      "url": "https,http://localhost:8080/fhir/MedicationAdministration?_profile=https%3A%2F%2Fwww.medizininformatik-initiative.de%2Ffhir%2Fcore%2Fmodul-medikation%2FStructureDefinition%2FMedicationAdministration&_summary=count&_count=50&__t=18756"
    }
  ],
  "resourceType": "Bundle"
}
```
100% of the `MedicationAdministration` resources (27669756) have this profile set.
This blaze instance has a default configuration except `-Xmx8g`.

**Comment by alexanderkiel** [comment]
Sorry for the late answer. I missed your issue. It's a known limitation that Blaze can only count 1 million resources per second in best case if all relevant cases are filled. You can read more about it in [FHIR Search Performance](https://samply.github.io/blaze/performance/fhir-search.html). Important for pure resource counting is the resource handle cache and the RocksDB block cache.

Blaze provides a Prometheus metrics endpoint on port 8081 by default. The documentation is still lacking in this regard, but you can find a Grafana dashboard [here](https://github.com/samply/blaze/tree/master/compose).

If you tune your cache settings accordantly, you can achieve at best a query time of about 30 seconds in your case. The maximum heap size has no impact in resource counting. 

Please also note that Blaze was not optimised for just counting all resources of a particular type. As I like to have Blaze faster here, unfortunately the MII Dashboard queries are slow for now, but they will finish.
